name: awol
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# -------------------------------------

  auto_size_text: ^2.1.0
  badges: ^1.1.0
  cupertino_icons: ^0.1.2
  datetime_picker_formfield: ^0.4.2
  device_info: ^0.4.0+2
  firebase_analytics: ^5.0.1
  firebase_core: ^0.4.0+9
  firebase_dynamic_links: ^0.5.0+1
  flip_card: ^0.4.1
  fluintl: ^0.1.3
  flutter_slidable: ^0.5.3
  flutter_swiper: ^1.1.6
  flutter_xlider: ^2.4.3
  folding_cell: ^0.1.2
  font_awesome_flutter: ^8.5.0
  get_it: ^1.0.3+2
  http: ^0.12.0+2
  intl: ^0.15.8
  path_provider: ^1.1.0
  pull_to_refresh: ^1.3.7
  rxdart: ^0.22.0
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.2
  table_calendar: ^2.0.1
  trotter: ^1.0.2
  url_launcher: ^5.1.2
  vector_math: ^2.0.8

# -------------------------------------

dev_dependencies:
  image: 2.1.4
  flutter_launcher_icons: ^0.7.2+1
  mockito: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# -------------------------------------

  assets:
    - assets/wareHouse.jpeg
    - assets/dpInitials.png
